gcp:
  project: "google.com:robsantos-agamotto"
  dataset: "agamotto_measure"
  bigquery_table: "agamotto_count"
  save_to_bigquery: True
timezone: 'America/Sao_Paulo'
location:
  #-23.563522,-46.6526872
  #-23.5705533,-46.6435249
  #-23.5418067,-46.6582475
  latlong: "-23.5705533,-46.6435249"
  id: 12
  #Fastshop - Shopping Cidade de São Paulo
  #Fastshop - Shopping Pátio Paulista 
  #Fastshop - Shopping Higienópolis
  name: "Fastshop - Shopping Pátio Paulista"
model:
  tensorflow_dataset: 'coco/2017'
  load_dataset: False
  epochs: 6
  train_dataset_size: 100
  val_dataset_size: 50
  save_weights_dir: agamotto_train
  load_weights_dir: agamotto_data
  #create load_weights_url
  #create load_weights_version
  num_classes: 1
  batch_size: 1
  confidence_threshold: 0.35
  model_optimizer_momentum: 0.9
  train: False
#create is_stream
video:
  input_location: "shopping_2.mp4"
  write_output_fps: 5
  read_interval: 1
  output_location: "output.avi"
  is_stream: False
